pagination support in wait

diff --git a/src/commands/trigger-workflows-for-all-modified.yml b/src/commands/trigger-workflows-for-all-modified.yml
--- a/src/commands/trigger-workflows-for-all-modified.yml
+++ b/src/commands/trigger-workflows-for-all-modified.yml
@@ -270,13 +270,22 @@ steps:
           echo "Waiting for workflow: ${workflow_id} to complete"
 
           while true; do
-            # TODO: Need to support pagination somehow
             workflow_status=/tmp/swissknife/workflow_status.json
-            curl --silent "https://circleci.com/api/v2/pipeline/${workflow_id}/workflow?circle-token=${CIRCLE_TOKEN}" > ${workflow_status}
+            rm -f ${workflow_status}
+            page=""
+            while true; do
+              # pagination
+              last_workflow_status=/tmp/swissknife/last_workflow_status.json
+              curl --silent "https://circleci.com/api/v2/pipeline/${workflow_id}/workflow?circle-token=${CIRCLE_TOKEN}${page}" | tee ${last_workflow_status} | jq -r '.items[]' >> ${workflow_status}
+              page="&page-token=$(jq -cr '.next_page_token' ${last_workflow_status})"
+              if (( $? )); then # the jq quits with error with next_page_token is null/missing
+                break
+              fi
+            done
 
-            total=$(jq '.items | length' ${workflow_status})
-            running=$(jq '.items | map(select(.status == "running")) | length' ${workflow_status})
-            success=$(jq '.items | map(select(.status == "success")) | length' ${workflow_status})
+            total=$(jq -s 'length' ${workflow_status})
+            running=$(jq -s 'map(select(.status == "running")) | length' ${workflow_status})
+            success=$(jq -s 'map(select(.status == "success")) | length' ${workflow_status})
             echo "total: ${total}, running: ${running}, success: ${success}"
             if (( $total == 0 || $running > 0 )); then
               echo "Going to sleep for << parameters.sleep-time-between-checks >>"
@@ -287,7 +296,9 @@ steps:
             else
               cat ${workflow_status}
               echo ""
-              echo "The above jobs have at least one non-success status, this will now fail"
+              echo "The following jobs have at least one non-success status, this will now fail:"
+              jq -r 'select(.status != "success") | .name + " (" + .status + "): https://app.circleci.com/pipelines/" + .project_slug + "/" + (.pipeline_number | tostring) + "/workflows/" + .id ' ${workflow_status}
+              echo "Bye!"
               exit 1
             fi
           done
