Updated Wait for Job and Add new Command for Approving Hold Jobs (#103)
* Updated wait_for_job to handle multiple jobs. Also created a command to approve on hold jobs by name

diff --git a/src/commands/wait_for_job.yml b/src/commands/wait_for_job.yml
--- a/src/commands/wait_for_job.yml
+++ b/src/commands/wait_for_job.yml
@@ -1,12 +1,12 @@
 description: |
-  This command waits for another job in this workflow. Since right now Circle CI doesnt let
+  This command waits for a job(s) in this workflow. Since right now Circle CI doesn't let
   you queue up jobs irrespective of whether they fail or not. This is a faux queue where
   the command stalls till the other job succeeds.
   This requires a Circle CI token be set as $CIRCLE_TOKEN
 
 parameters:
   job-name:
-    description: The job on which to wait. If job not found continue immediately
+    description: The job or jobs on which to wait. If job not found continue immediately. For multiple jobs the list must be comma separated.
     type: string
   max-wait-time:
     description: |
@@ -27,6 +27,12 @@ parameters:
       '*' the wait will run only on the specified branch
     type: string
     default: "*"
+  circleci-api-key:
+    default: CIRCLE_TOKEN
+    description: >-
+      In case you use a different Environment Variable Name than
+      CIRCLE_TOKEN, supply it here.
+    type: env_var_name
 
 steps:
   - run:
@@ -37,8 +43,8 @@ steps:
           exit 1
         fi
         hash jq 2>/dev/null || { echo >&2 "jq is not installed.  Aborting."; exit 1; }
-        if [[ "$CIRCLE_TOKEN" == "" ]]; then
-          echo "CIRCLE_TOKEN not set. Set a token to access the circle API in the env var CIRCLE_TOKEN";
+        if [[ "$<< parameters.circleci-api-key >>" == "" ]]; then
+          echo "<< parameters.circleci-api-key >> not set. Set a token to access the circle API in the env var << parameters.circleci-api-key >>";
           exit 1;
         fi
 
@@ -47,42 +53,51 @@ steps:
           exit 0;
         fi
 
-        api_endpoint="api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job"
-
         mkdir -p /tmp/swissknife
 
-        # This is a global variable used to get return value for get_job_status
-        job_status=""
-        job_number=""
 
         get_job_status() {
-          wf_url="https://circleci.com/$api_endpoint?circle-token=${CIRCLE_TOKEN}"
-          curl -f -s $wf_url > /tmp/swissknife/wf_$CIRCLE_WORKFLOW_ID.json
-          job_status=$(jq -r '.items[] | select(.name=="<< parameters.job-name >>") | .status' /tmp/swissknife/wf_$CIRCLE_WORKFLOW_ID.json)
-          job_number=$(jq -r '.items[] | select(.name=="<< parameters.job-name >>") | .job_number' /tmp/swissknife/wf_$CIRCLE_WORKFLOW_ID.json)
+          local NAME_OF_JOB="$1"
+          local STATUS=""
+          local NUMBER=""
+
+          curl --header "Circle-Token: $<< parameters.circleci-api-key >>" -f -s https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job > /tmp/swissknife/wf_$CIRCLE_WORKFLOW_ID.json
+          STATUS=$(jq -r ".items[] | select(.name==\"${NAME_OF_JOB}\") | .status" /tmp/swissknife/wf_$CIRCLE_WORKFLOW_ID.json)
+          NUMBER=$(jq -r ".items[] | select(.name==\"${NAME_OF_JOB}\") | .job_number" /tmp/swissknife/wf_$CIRCLE_WORKFLOW_ID.json)
+          echo "${STATUS} ${NUMBER}"
         }
 
-        current_wait_time=0
 
-        while true; do
-          get_job_status
-          if [[ "$job_status" == "success" || "$job_status" == "failed" || "$job_status" == "canceled" || "$job_status" == "" ]]; then
-            echo "Its finally my turn. exiting"
-            exit 0
-          else
-            echo "Looks like the other guy ($job_number) is still not done ($job_status)."
-            echo "Going to sleep for << parameters.sleep-time-between-checks >>"
-            sleep << parameters.sleep-time-between-checks >>
-            current_wait_time=$(( current_wait_time + << parameters.sleep-time-between-checks >> ))
-          fi
+        job_list="<< parameters.job-name >>"
 
-          if (( $current_wait_time > << parameters.max-wait-time >> )); then
-            if [[ "<< parameters.kill-gracefully >>" == "true" ]]; then
-              echo "Proceeding with future steps";
-              exit 0;
+        for job_name in ${job_list//,/ }
+        do
+          # Reset job status, job number and wait time
+          job_status=""
+          job_number=""
+          current_wait_time=0
+
+          echo "Starting to check status of ${job_name}"
+          while true; do
+            read job_status job_number < <(get_job_status ${job_name})
+            if [[ "$job_status" == "success" || "$job_status" == "failed" || "$job_status" == "canceled" || "$job_status" == "" ]]; then
+              echo "Job, ${job_name}, has completed!"
+              break
             else
-              echo "Failing job by exiting forcefully";
-              exit 1;
+              echo "Looks like the other guy ($job_number) is still not done ($job_status)."
+              echo "Going to sleep for << parameters.sleep-time-between-checks >>"
+              sleep << parameters.sleep-time-between-checks >>
+              current_wait_time=$(( current_wait_time + << parameters.sleep-time-between-checks >> ))
             fi
-          fi
+
+            if (( $current_wait_time > << parameters.max-wait-time >> )); then
+              if [[ "<< parameters.kill-gracefully >>" == "true" ]]; then
+                echo "Proceeding with future steps";
+                break
+              else
+                echo "Failing job by exiting forcefully";
+                exit 1;
+              fi
+            fi
+          done
         done
